# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-05 11:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0008_auto_20160604_1850'),
    ]

    operations = [
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.CharField(blank=True, choices=[('3', '3'), ('4', '4'), ('5', '5'), ('zachet', '\u0417\u0430\u0447\u0451\u0442')], default='', max_length=15, verbose_name='\u043e\u0446\u0435\u043d\u043a\u0430')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Student', verbose_name='\u0441\u0442\u0443\u0434\u0435\u043d\u0442')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.SemesterSubject', verbose_name='\u043f\u0440\u0435\u0434\u043c\u0435\u0442')),
            ],
            options={
                'verbose_name': '\u0423\u0441\u043f\u0435\u0432\u0430\u0435\u043c\u043e\u0441\u0442\u044c',
                'verbose_name_plural': '\u0423\u0441\u043f\u0435\u0432\u0430\u0435\u043c\u043e\u0441\u0442\u044c',
            },
        ),
    ]
