# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-18 18:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=100, verbose_name='\u0444\u0430\u043c\u0438\u043b\u0438\u044f')),
                ('first_name', models.CharField(max_length=100, verbose_name='\u0438\u043c\u044f')),
                ('middle_name', models.CharField(max_length=100, verbose_name='\u043e\u0442\u0447\u0435\u0441\u0442\u0432\u043e')),
            ],
            options={
                'verbose_name': '\u0441\u0442\u0443\u0434\u0435\u043d\u0442',
                'verbose_name_plural': '\u0441\u0442\u0443\u0434\u0435\u043d\u0442\u044b',
            },
        ),
        migrations.CreateModel(
            name='StudentGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='\u043d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('start_year', models.PositiveIntegerField(verbose_name='\u0433\u043e\u0434 \u043f\u043e\u0441\u0442\u0443\u043f\u043b\u0435\u043d\u0438\u044f')),
                ('group_type', models.CharField(choices=[('bachelor', '\u0411\u0430\u043a\u0430\u043b\u0430\u0432\u0440'), ('magister', '\u041c\u0430\u0433\u0438\u0441\u0442\u0440')], max_length=20, verbose_name='\u0442\u0438\u043f \u043e\u0431\u0443\u0447\u0435\u043d\u0438\u044f')),
            ],
            options={
                'verbose_name': '\u0433\u0440\u0443\u043f\u043f\u0430',
                'verbose_name_plural': '\u0433\u0440\u0443\u043f\u043f\u044b',
            },
        ),
        migrations.AddField(
            model_name='student',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.StudentGroup', verbose_name='\u0433\u0440\u0443\u043f\u043f\u0430'),
        ),
    ]
