# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-18 18:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=100, verbose_name='\u0444\u0430\u043c\u0438\u043b\u0438\u044f')),
                ('first_name', models.CharField(max_length=100, verbose_name='\u0438\u043c\u044f')),
                ('middle_name', models.CharField(blank=True, default='', max_length=100, verbose_name='\u043e\u0442\u0447\u0435\u0441\u0442\u0432\u043e')),
                ('position', models.CharField(blank=True, default='', max_length=100, verbose_name='\u0434\u043e\u043b\u0436\u043d\u043e\u0441\u0442\u044c')),
            ],
            options={
                'verbose_name': '\u043f\u0440\u0435\u043f\u043e\u0434\u0430\u0432\u0430\u0442\u0435\u043b\u044c',
                'verbose_name_plural': '\u043f\u0440\u0435\u043f\u043e\u0434\u0430\u0432\u0430\u0442\u0435\u043b\u0438',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='\u043d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('subject_type', models.CharField(choices=[('exam', '\u042d\u043a\u0437\u0430\u043c\u0435\u043d'), ('credit', '\u0417\u0430\u0447\u0451\u0442')], max_length=20, verbose_name='\u0442\u0438\u043f \u044d\u043a\u0437\u0430\u043c\u0435\u043d\u0430')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Staff', verbose_name='\u043f\u0440\u0435\u043f\u043e\u0434\u0430\u0432\u0430\u0442\u0435\u043b\u044c')),
            ],
            options={
                'verbose_name': '\u0434\u0438\u0441\u0446\u0438\u043f\u043b\u0438\u043d\u0430',
                'verbose_name_plural': '\u0434\u0438\u0441\u0446\u0438\u043f\u043b\u0438\u043d\u044b',
            },
        ),
        migrations.AlterField(
            model_name='student',
            name='middle_name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='\u043e\u0442\u0447\u0435\u0441\u0442\u0432\u043e'),
        ),
    ]
