# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-04 13:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20160526_0056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semesterconfiguration',
            name='first_semester_end',
            field=models.DateField(null=True, verbose_name='\u043a\u043e\u043d\u0435\u0446 \u043f\u0435\u0440\u0432\u043e\u0433\u043e \u0441\u0435\u043c\u0435\u0441\u0442\u0440\u0430'),
        ),
        migrations.AlterField(
            model_name='semesterconfiguration',
            name='first_semester_start',
            field=models.DateField(null=True, verbose_name='\u043d\u0430\u0447\u0430\u043b\u043e \u043f\u0435\u0440\u0432\u043e\u0433\u043e \u0441\u0435\u043c\u0435\u0441\u0442\u0440\u0430'),
        ),
        migrations.AlterField(
            model_name='semesterconfiguration',
            name='second_semester_end',
            field=models.DateField(null=True, verbose_name='\u043a\u043e\u043d\u0435\u0446 \u0432\u0442\u043e\u0440\u043e\u0433\u043e \u0441\u0435\u043c\u0435\u0441\u0442\u0440\u0430'),
        ),
        migrations.AlterField(
            model_name='semesterconfiguration',
            name='second_semester_start',
            field=models.DateField(null=True, verbose_name='\u043d\u0430\u0447\u0430\u043b\u043e \u0432\u0442\u043e\u0440\u043e\u0433\u043e \u0441\u0435\u043c\u0435\u0441\u0442\u0440\u0430'),
        ),
    ]
