# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-05 12:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0008_auto_20160604_1850'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thesis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.TextField(blank=True, default='', verbose_name='\u0442\u0435\u043c\u0430')),
                ('progress', models.PositiveIntegerField(default=0, verbose_name='\u043f\u0440\u043e\u0433\u0440\u0435\u0441\u0441')),
                ('last_change_date', models.DateField(blank=True, null=True, verbose_name='\u0434\u0430\u0442\u0430 \u043f\u043e\u0441\u043b\u0435\u0434\u043d\u0435\u0433\u043e \u0438\u0437\u043c\u0435\u043d\u0435\u043d\u0438\u044f')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Staff', verbose_name='\u043f\u0440\u043e\u0433\u0440\u0435\u0441\u0441')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Semester', verbose_name='\u0441\u0435\u043c\u0435\u0441\u0442\u0440')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Student', verbose_name='\u0441\u0442\u0443\u0434\u0435\u043d\u0442')),
            ],
            options={
                'verbose_name': '\u0440\u0430\u0431\u043e\u0442\u0430',
                'verbose_name_plural': '\u043a\u0443\u0440\u0441\u043e\u0432\u044b\u0435 \u0438 \u0434\u0438\u043f\u043b\u043e\u043c\u044b',
            },
        ),
    ]
