# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-05 13:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('thesis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thesis',
            name='professor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Staff', verbose_name='\u043f\u0440\u043e\u0433\u0440\u0435\u0441\u0441'),
        ),
    ]
