# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-22 11:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('thesis', '0002_auto_20160605_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thesis',
            name='professor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Staff', verbose_name='\u043d\u0430\u0443\u0447\u043d\u044b\u0439 \u0440\u0443\u043a\u043e\u0432\u043e\u0434\u0438\u0442\u0435\u043b\u044c'),
        ),
    ]
