# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-18 19:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_auto_20160518_2257'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attended', models.BooleanField(verbose_name='\u043f\u0440\u0438\u0441\u0443\u0442\u0441\u0442\u0432\u043e\u0432\u0430\u043b')),
            ],
            options={
                'verbose_name': '\u043f\u043e\u0441\u0435\u0449\u0435\u043d\u0438\u0435',
                'verbose_name_plural': '\u043f\u043e\u0441\u0435\u0449\u0435\u043d\u0438\u044f',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='\u0434\u0430\u0442\u0430')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.StudentGroup', verbose_name='\u0433\u0440\u0443\u043f\u043f\u0430')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Subject', verbose_name='\u043f\u0440\u0435\u0434\u043c\u0435\u0442')),
            ],
            options={
                'verbose_name': '\u0437\u0430\u043d\u044f\u0442\u0438\u0435',
                'verbose_name_plural': '\u0437\u0430\u043d\u044f\u0442\u0438\u044f',
            },
        ),
        migrations.AddField(
            model_name='attendance',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.Lesson', verbose_name='\u0437\u0430\u043d\u044f\u0442\u0438\u0435'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Student', verbose_name='\u0441\u0442\u0443\u0434\u0435\u043d\u0442'),
        ),
    ]
