# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-18 21:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='attended',
            field=models.BooleanField(default=False, verbose_name='\u043f\u0440\u0438\u0441\u0443\u0442\u0441\u0442\u0432\u043e\u0432\u0430\u043b'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.SemesterSubject', verbose_name='\u043f\u0440\u0435\u0434\u043c\u0435\u0442'),
        ),
    ]
