# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-24 15:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_auto_20160519_0130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='core.SemesterSubject', verbose_name='\u043f\u0440\u0435\u0434\u043c\u0435\u0442'),
        ),
    ]
