# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-25 20:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_auto_20160519_0130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='group',
        )
    ]
