# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-25 20:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20160519_0111'),
        ('attendance', '0003_auto_20160526_0023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='subject',
        ),
        migrations.AddField(
            model_name='lesson',
            name='semester_subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='core.SemesterSubject', verbose_name='\u043f\u0440\u0435\u0434\u043c\u0435\u0442'),
            preserve_default=False,
        ),
    ]
